Repository BastionOfEndeavor/BastionOfEndeavor2_VR, pull requests merged in 2022-11, with the labels that each got.

#217 Добавляет глагол для вывода подтипов
  russian/_verbs_ru.dm
Labels: Эндевор

#218 Локализация модуля Списка рантаймов
  code/modules/error_handler/error_handler.dm
  code/modules/error_handler/error_viewer.dm
Labels: Эндевор, Локализация

#233 [ЗЕРКАЛО] Various text-box QoL stuff
  code/modules/mob/say_vr.dm
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Апстрим

#232 [ЗЕРКАЛО] Baton Lanyard
  code/modules/clothing/under/accessories/holster_vr.dm
  icons/inventory/accessory/item.dmi
  icons/inventory/accessory/mob.dmi
Labels: Апстрим

#230 [ЗЕРКАЛО] Removes crab claws, fixes belly tattoo
  code/modules/mob/new_player/sprite_accessories_extra_vr.dm
  icons/mob/human_races/markings.dmi
  icons/mob/human_races/markings_vr.dmi
Labels: Апстрим

#229 [ЗЕРКАЛО] Fixes two lobby bugs
  code/modules/mob/say_vr.dm
Labels: Апстрим

#228 [ЗЕРКАЛО] On mob examine
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Апстрим

#227 [ЗЕРКАЛО] Bump @xmldom/xmldom from 0.7.5 to 0.7.8 in /tgui
  tgui/yarn.lock
Labels: Апстрим

#226 [ЗЕРКАЛО] Allergen Effect/Reaction Traits
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
Labels: Апстрим

#224 [ЗЕРКАЛО] Blocks creation of shelter pods in the Fish Farm and Public Garden
  maps/groundbase/groundbase_things.dm
  maps/tether/tether_things.dm
Labels: Апстрим

#222 [ЗЕРКАЛО] remove xenoarch tools from mining vender
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Labels: Апстрим

#221 [ЗЕРКАЛО] Back to SD
  vorestation.dme
Labels: Апстрим

#234 [ЗЕРКАЛО] Permit (Some) Linebreaks
  code/_helpers/text.dm
Labels: Апстрим

#238 [ЗЕРКАЛО] Map swap
  vorestation.dme
Labels: Апстрим

#239 [ЗЕРКАЛО] Xenochimera Fix for Numbing Fangs/Sharp Melee overriding Claws
  code/modules/mob/living/carbon/human/species/station/xenochimera_trait_vr.dm
Labels: Апстрим

#240 [ЗЕРКАЛО] Makes some species specific emotes general
  code/modules/mob/living/carbon/human/emote.dm
Labels: Апстрим

#241 [ЗЕРКАЛО] ISV LUNA - A Ship!
  maps/offmap_vr/om_ships/lunaship.dm
  maps/offmap_vr/om_ships/lunaship.dmm
  vorestation.dme
Labels: Апстрим

#242 [ЗЕРКАЛО] Buffs paperwork on Stellar Delight (adds paperbin to captain's office, shredder to meeting room)
  maps/stellar_delight/stellar_delight2.dmm
Labels: Апстрим

#243 [ЗЕРКАЛО] AR-Bs Employment Records
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/examine_vr.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Апстрим

#244 [ЗЕРКАЛО] Hopefully fixes corner sofas
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  icons/obj/sofas.dmi
Labels: Апстрим

#245 [ЗЕРКАЛО] Fixes prommie glow
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defines.dm
Labels: Апстрим

#246 [ЗЕРКАЛО] Adds sect drone taurhalves and wvag versions of existing fat taurs
  code/modules/mob/new_player/sprite_accessories_taur_vr.dm
  icons/mob/vore/taurs_vr.dmi
Labels: Апстрим

#247 [ЗЕРКАЛО] Species Alcohol Mod Cleanup
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
  code/modules/reagents/reagents/dispenser.dm
Labels: Апстрим

#248 [ЗЕРКАЛО] Bump loader-utils from 2.0.2 to 2.0.3 in /tgui
  tgui/yarn.lock
Labels: Апстрим

#249 [ЗЕРКАЛО] Makes contaminated boxes not fall apart
  code/modules/vore/eating/contaminate_vr.dm
Labels: Апстрим

#250 [ЗЕРКАЛО] Makes hedge trimmers instakill vines
  code/modules/hydroponics/trays/tray_tools.dm
Labels: Апстрим

#251 [ЗЕРКАЛО] Adds 'Rancher' alt title for botanist.
  code/game/jobs/job/civilian_vr.dm
Labels: Апстрим

#252 [ЗЕРКАЛО] Fix bump teleporter
  code/game/objects/effects/bump_teleporter.dm
Labels: Апстрим

#254 [ЗЕРКАЛО] Shhhh
  vorestation.dme
Labels: Апстрим

#255 [ЗЕРКАЛО] equip_special
  code/modules/clothing/under/miscellaneous_vr.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Апстрим

#256 [ЗЕРКАЛО] Shortwave Headsets Crate
  code/datums/supplypacks/misc_vr.dm
Labels: Апстрим

#257 [ЗЕРКАЛО] Bump loader-utils from 2.0.3 to 2.0.4 in /tgui
  tgui/yarn.lock
Labels: Апстрим

#258 [ЗЕРКАЛО] Update air_traffic.dm
  code/modules/busy_space_vr/air_traffic.dm
Labels: Апстрим

#259 [ЗЕРКАЛО] Fixes comfy chair recipies being removed by broken mirror
  code/modules/materials/materials/metals/steel.dm
  maps/offmap_vr/talon/talon_v2.dmm
Labels: Апстрим

#260 [ЗЕРКАЛО] ISV LUNA - Adjustments
  maps/offmap_vr/om_ships/lunaship.dmm
Labels: Апстрим

#261 [ЗЕРКАЛО] Pandora's Fox-orb custom plush
  code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
  code/modules/vore/fluffstuff/custom_items_vr.dm
  icons/vore/custom_items_vr.dmi
Labels: Апстрим

#262 [ЗЕРКАЛО] Ticket Printer!
  code/datums/roundstats/roundstats.dm
  code/game/objects/items/devices/ticket_printer.dm
  code/modules/admin/admin_verb_lists_vr.dm
  code/modules/admin/admin_verbs_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  icons/obj/bureaucracy_vr.dmi
  icons/obj/device_vr.dmi
  maps/groundbase/gb-z1.dmm
  maps/stellar_delight/stellar_delight1.dmm
  maps/stellar_delight/stellar_delight3.dmm
  maps/tether/tether-02-surface2.dmm
  maps/tether/tether-03-surface3.dmm
  sound/items/ticket_printer.ogg
  vorestation.dme
Labels: Апстрим

#263 [ЗЕРКАЛО] removes meme reaction, adds sickness to regen
  code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
  code/modules/reagents/reactions/instant/instant_vr.dm
Labels: Апстрим

#264 [ЗЕРКАЛО] spidaurs
  code/modules/mob/new_player/sprite_accessories_taur_vr.dm
  icons/mob/vore/taurs_vr.dmi
Labels: Апстрим

#265 [ЗЕРКАЛО] Stellar Delight Upgrades NOV 2022
  maps/stellar_delight/stellar_delight1.dmm
  maps/stellar_delight/stellar_delight2.dmm
  maps/stellar_delight/stellar_delight3.dmm
Labels: Апстрим

#266 [ЗЕРКАЛО] Trash pile adjustments
  code/game/objects/structures/trash_pile_vr.dm
  code/modules/clothing/under/miscellaneous_vr.dm
Labels: Апстрим

#267 [ЗЕРКАЛО] Makes the unmaintained antique behave like one
  code/modules/projectiles/guns/energy/laser.dm
Labels: Апстрим

#268 [ЗЕРКАЛО] Adds ability for items to be whitelisted for protean blob-drop; adds that to Freyr's mask
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_blob.dm
  code/modules/vore/fluffstuff/custom_clothes_vr.dm
Labels: Апстрим

#269 [ЗЕРКАЛО] Teshari screaming noise. *teshscream
  code/modules/emotes/definitions/audible.dm
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/teshscream.ogg
Labels: Апстрим

#270 [ЗЕРКАЛО] Gives teshari missing hat + mask sprites.
  code/modules/clothing/head/misc_special_vr.dm
  code/modules/clothing/head/misc_vr.dm
  code/modules/clothing/masks/gasmask_vr.dm
  code/modules/clothing/masks/miscellaneous_vr.dm
  code/modules/clothing/suits/wiz_robe.dm
  icons/inventory/face/mob_vr_teshari.dmi
  icons/inventory/head/mob_vr_teshari.dmi
  vorestation.dme
Labels: Апстрим

#271 [ЗЕРКАЛО] Up ports bug sprites fitting for teshari (Wings, tails and ears)
  code/modules/mob/new_player/sprite_accessories_ear_vr.dm
  code/modules/mob/new_player/sprite_accessories_tail_vr.dm
  code/modules/mob/new_player/sprite_accessories_wing_vr.dm
  icons/mob/vore/ears_vr.dmi
  icons/mob/vore/tails_vr.dmi
  icons/mob/vore/wings_vr.dmi
Labels: Апстрим

#272 [ЗЕРКАЛО] Back to SD
  vorestation.dme
Labels: Апстрим

#275 [ЗЕРКАЛО] Bump pillow from 9.0.1 to 9.3.0 in /tools/mapmerge2
  tools/mapmerge2/requirements.txt
Labels: Апстрим

#276 [ЗЕРКАЛО] Bump fastify from 3.29.0 to 3.29.4 in /tgui
  tgui/packages/tgui-bench/package.json
  tgui/yarn.lock
Labels: Апстрим

#277 [ЗЕРКАЛО] Adjust Security Ticket
  code/modules/admin/admin_verbs_vr.dm
Labels: Апстрим

#278 Рефакторит лист падежей в подлисты
  code/controllers/subsystems/supply.dm
  code/controllers/subsystems/ticker.dm
  code/modules/error_handler/error_viewer.dm
  russian/_cases_revamped_ru.dm
  russian/_cases_ru.dm
  russian/_client_cases_ru.dm
  russian/_russian_ru.dm
  russian/_verbs_ru.dm
Labels: Эндевор
